175 order detail ajilgaand orullah
Pinecone-2024-LEAP-1G/Uberdash pull request #189
Opened 2024-12-06 05:57 UTC by 14Berhee

<img width="617" alt="Screenshot 2024-12-05 at 21 57 12" src="https://github.com/user-attachments/assets/edbd36e7-f961-4025-8992-686e1b4ac6b0">
<img width="1869" alt="Screenshot 2024-12-05 at 21 57 23" src="https://github.com/user-attachments/assets/56cf8151-8c08-421c-b07b-8cc01abab767">

2024-12-06 06:01 UTC, Baatarvant approved these changes

2024-12-06 06:01 UTC, Baatarvant commented on src/components/AddOrderModal.tsx
> +  menuItem?: Food; // Made menuItem optional for safety
Ene food geed tupe-iin MenuItem bolgoodhooch

2024-12-06 06:01 UTC, Baatarvant commented on src/components/restaurant/MenuItemLastCard.tsx
> +          <p>91%</p>
Ene yun hatuu huvi bile?

2024-12-06 06:02 UTC, Baatarvant requested changes
Comment bichiv

2024-12-09 01:23 UTC, sumiyab approved these changes

2024-12-09 01:30 UTC, sumiyab requested changes

2024-12-09 01:30 UTC, sumiyab commented on src/components/AddOrderModal.tsx
> +type menuItem = {
ene type neriig Tomoor bichiii

2024-12-09 02:51 UTC, Baatarvant approved these changes

2024-12-09 02:51 UTC, merged